# Generated by Django 3.1.3 on 2020-11-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='created',
        ),
        migrations.AddField(
            model_name='insight',
            name='label',
            field=models.CharField(default='aa', max_length=200, verbose_name='作成日'),
            preserve_default=False,
        ),
    ]
