# Generated by Django 3.1.3 on 2020-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=1, verbose_name='投稿数'),
            preserve_default=False,
        ),
    ]
