# Generated by Django 3.1.3 on 2020-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='label',
            field=models.CharField(max_length=100, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(max_length=100, verbose_name='投稿日'),
        ),
    ]
